version: "3.7"

services:
  web:
    build: ./blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./blog/:/usr/src/blog/
    ports:
      - 8000:8000
    env_file:
      - ./blog/.env.dev
    depends_on: 
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=grzegorz
      - POSTGRES_PASSWORD=grzegorz123
      - POSTGRES_DB=blog

volumes:
  postgres-data:
